name: Ruby

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2', '3.3', 'jruby', 'truffleruby']
        platform: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - ruby-version: truffleruby
            platform: windows-latest
          - ruby-version: jruby
            platform: windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run tests
      run: |
        if [[ "$(ruby -v | awk '{print $2}')" == 2.7.8* ]]; then
          gem install bundler -v 2.4.22 --no-document
        else
          gem install bundler --no-document
        fi
        bundle install --quiet
        bundle exec rspec
